import express, { Request, Response } from 'express';
import dotenv from 'dotenv';
import bot from './bot';

dotenv.config();

const app = express();
const port = process.env.PORT || 3000;

// The secret path is a random string generated by telegraf to secure the webhook
const secretPath = `/telegraf/${bot.secretPathComponent()}`;

// We need to parse the body to get the update from Telegram
app.use(express.json());

// Set the bot API endpoint
app.use(bot.webhookCallback(secretPath));

app.get('/', (req: Request, res: Response) => {
  res.send('Hello, World!');
});

app.listen(port, async () => {
  console.log(`Server is running at http://localhost:${port}`);
  
  const webhookDomain = process.env.WEBHOOK_DOMAIN;
  if (!webhookDomain) {
    console.error('WEBHOOK_DOMAIN must be provided in .env');
    process.exit(1);
  }

  // Set the webhook
  const webhookUrl = `${webhookDomain}${secretPath}`;
  await bot.telegram.setWebhook(webhookUrl);
  console.log(`Webhook set to ${webhookUrl}`);
});
